# Generated by Django 4.2 on 2023-07-29 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_job_category_alter_job_level_alter_job_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company_website",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="logo",
        ),
    ]
