# Generated by Django 4.2 on 2023-07-29 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "svg"]
                    )
                ],
            ),
        ),
    ]
